// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
import 'dart:ffi' as ffi;

/// Bindings for the integration tests
class IntegrationTestsFfi {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  IntegrationTestsFfi(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  IntegrationTestsFfi.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  int initialize(
    InitData init_data,
  ) {
    return _initialize(
      init_data,
    );
  }

  late final _initializePtr =
      _lookup<ffi.NativeFunction<ffi.Int32 Function(InitData)>>('initialize');
  late final _initialize = _initializePtr.asFunction<int Function(InitData)>();

  int setup_cmd_handler(
    int respond_to,
  ) {
    return _setup_cmd_handler(
      respond_to,
    );
  }

  late final _setup_cmd_handlerPtr =
      _lookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Int64)>>(
          'setup_cmd_handler');
  late final _setup_cmd_handler =
      _setup_cmd_handlerPtr.asFunction<int Function(int)>();
}

typedef InitData = ffi.Pointer<ffi.Void>;
