name: integration_tests
description: A starting point for Dart libraries or applications.
version: 0.1.0

environment:
  sdk: '>=2.17.3 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.1
  ffigen: '^6.0.1'

