name: 'cargo-sort'
description: 'Installs cargo-sort'
runs:
  using: "composite"
  steps:
    - shell: bash
      working-directory: ${{ runner.temp }}
      env:
        LINUX_URL: https://github.com/DevinR528/cargo-sort/releases/download/v1.0.7/cargo-sort-x86_64-unknown-linux-gnu.tar.gz
        LINUX_CHECKSUM: ff15079ef55abd1db59a32ff703d4b9e605fc83cab03e810dd5488db36e357cc624573d94252d484b8eb8e74f62f9ef9667d7ad78569498bdb481173831305d8
        MACOS_URL: https://github.com/DevinR528/cargo-sort/releases/download/v1.0.7/cargo-sort-x86_64-apple-darwin.tar.gz
        MACOS_CHECKSUM: 5c9ff473f97a1105ee9e88642e906bfb41ef5740db9ef08e19c470e9a233077a77e3816617cc6dca319e275fbefaa805c2d1c1532845dcc7cb4cc817c388d60
      run: |
        if [ ${{ runner.os }} == "Linux" ]; then
          URL=${{ env.LINUX_URL }}
          CHECKSUM=${{ env.LINUX_CHECKSUM }}
        elif [ ${{ runner.os }} == "macOS" ]; then
          URL=${{ env.MACOS_URL }}
          CHECKSUM=${{ env.MACOS_CHECKSUM }}
        else
          echo "::error cargo-sort for ${{ runner.os }} is not supported"
          exit 1
        fi
        wget -q -O cargo-sort $URL
        echo "$CHECKSUM *cargo-sort" | shasum -c -
        tar -xf cargo-sort
        chmod u+x cargo-sort
        mv cargo-sort $HOME/.cargo/bin

