name: Dart CI

on:
  push:
    paths:
      - '.github/workflows/dart_ci.yml'
      - 'dart-api-dl-sys/**'
      - 'dart-api-dl/**'
      - 'integration_tests/**'
      - 'integration-tests-bindings/**'


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  DART_VERSION: '2.14.4'
  DART_WORKSPACE: ${{ github.workspace }}/integration_tests
  RUST_WORKSPACE: ${{ github.workspace }}/

jobs:
  dart-format:
    name: dart-format
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3.0.2

      - name: Install dart
        uses: dart-lang/setup-dart@6a218f2413a3e78e9087f638a238f6b40893203d # v1.3
        with:
          sdk: ${{ env.DART_VERSION }}

      - name: Check formatting
        working-directory: ${{ env.DART_WORKSPACE }}
        run: dart format --output=none --set-exit-if-changed .

  integration-tests:
    name: integration-tests
    needs: dart-format
    runs-on: ubuntu-20.04
    timeout-minutes: 15
    steps:
      - name: Checkout repository
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3.0.2

      - name: Install rust toolchain
        working-directory: ${{ env.RUST_WORKSPACE }}
        run: rustup show

      - uses: Swatinem/rust-cache@cb2cf0cc7c5198d3364b9630e2c3d457f160790c # v1.4.0

      - name: Install dart
        uses: dart-lang/setup-dart@6a218f2413a3e78e9087f638a238f6b40893203d # v1.3
        with:
          sdk: ${{ env.DART_VERSION }}

      - name: Install Dart dependencies
        working-directory: ${{ env.DART_WORKSPACE }}
        run: dart pub get

      - name: Install clang for ffigen
        run: sudo apt-get install libclang-10-dev

      - name: Build Rust
        working-directory: ${{ env.RUST_WORKSPACE }}
        run: cargo build -p integration-tests-bindings

      - name: Unit test of integration test crate
        working-directory: ${{ env.RUST_WORKSPACE }}
        run: cargo test -p integration-tests-bindings

      - name: Analyze code
        working-directory: ${{ env.DART_WORKSPACE }}
        # We want to analyze code referring to `.ffigen.dart` files
        # which we only generate through rust because it's based
        # on macro generated code from rust.
        run: dart analyze --fatal-infos

      - name: Run tests
        working-directory: ${{ env.DART_WORKSPACE }}
        run: dart test

  # this is a helper that needs all the real leafs of the workflow.
  # It makes easier notify_main_failure because we only need to check
  # for this job
  ci-ok:
    name: ci-ok
    needs:
      - integration-tests
    runs-on: ubuntu-20.04
    steps:
      - name: Nothing to do
        run: echo "Helper job nothing to do"

  notify-main-failure:
    name: notify-main-failure
    needs: ci-ok
    # always() allows to run even if ci-ok is not successful
    # we only want this to run on the main branch
    if: always() && github.ref == 'refs/heads/main'
    runs-on: ubuntu-20.04
    steps:
      - name: Notify failure
        if: needs.ci-ok.result != 'success'
        uses: 8398a7/action-slack@a74b761b4089b5d730d813fbedcd2ec5d394f3af # v3.13.0
        with:
          status: custom
          fields: workflow, repo
          custom_payload: |
            {
              attachments: [{
                title: 'Main CI failed :warning:',
                color: 'danger',
                text: `CI: ${process.env.AS_WORKFLOW}\nRepository: ${process.env.AS_REPO}`,
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
