name: Rust CI

on:
  push:
    paths:
      - '.github/workflows/rust_ci.yml'
      - 'dart-api-dl/**'
      - 'dart-api-dl-sys/**'
      - 'dart-src'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  RUST_NIGHTLY: nightly-2022-05-19
  RUST_WORKSPACE: ${{ github.workspace }}/
  RUSTFLAGS: "-D warnings"
  DISABLE_AUTO_DART_FFIGEN: 1

jobs:
  cargo-format:
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3.0.2

      - name: Install rust toolchain
        working-directory: ${{ env.RUST_WORKSPACE }}
        run: rustup toolchain install ${{ env.RUST_NIGHTLY }} --component rustfmt

      - uses: Swatinem/rust-cache@cb2cf0cc7c5198d3364b9630e2c3d457f160790c # v1.4.0

      - name: cargo fmt
        working-directory: ${{ env.RUST_WORKSPACE }}
        run: cargo +${{ env.RUST_NIGHTLY }} fmt --all -- --check

  cargo-sort:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3.0.2

      - name: Install cargo-sort
        uses: ./.ci/install-cargo-sort

      - name: cargo sort
        run: cargo sort --grouped --workspace --check

  cargo-clippy:
    runs-on: ubuntu-20.04
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3.0.2

      - name: Install rust toolchain
        working-directory: ${{ env.RUST_WORKSPACE }}
        run: rustup show

      - uses: Swatinem/rust-cache@cb2cf0cc7c5198d3364b9630e2c3d457f160790c # v1.4.0

      - name: cargo clippy
        working-directory: ${{ env.RUST_WORKSPACE }}
        run: cargo clippy --all-targets -- --deny warnings

  cargo-test:
    timeout-minutes: 20
    strategy:
      matrix:
        os:
          - ubuntu-20.04
          - macos-11
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3.0.2

      - name: Install rust toolchain
        working-directory: ${{ env.RUST_WORKSPACE }}
        run: rustup show

      - uses: Swatinem/rust-cache@cb2cf0cc7c5198d3364b9630e2c3d457f160790c # v1.4.0

      - name: Run tests
        working-directory: ${{ env.RUST_WORKSPACE }}
        run: |
          cargo test --all-targets --quiet
          cargo test --doc --quiet

  cargo-doc:
    runs-on: ubuntu-20.04
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3.0.2

      - name: Install rust toolchain
        working-directory: ${{ env.RUST_WORKSPACE }}
        run: rustup show

      - uses: Swatinem/rust-cache@cb2cf0cc7c5198d3364b9630e2c3d457f160790c # v1.4.0

      - name: cargo doc
        working-directory: ${{ env.RUST_WORKSPACE }}
        run: cargo doc --all-features --no-deps --document-private-items
